/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb.tables.interfaces;


import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPlanet extends Serializable {

    /**
     * Getter for <code>appdb.planet.id</code>.
     */
    public UInteger getId();

    /**
     * Getter for <code>appdb.planet.name</code>.
     */
    public String getName();
}
