/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb;


import com.softwareaws.xray.examples.appdb.tables.Planet;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Appdb extends SchemaImpl {

    private static final long serialVersionUID = 758045248;

    /**
     * The reference instance of <code>appdb</code>
     */
    public static final Appdb APPDB = new Appdb();

    /**
     * The table <code>appdb.planet</code>.
     */
    public final Planet PLANET = com.softwareaws.xray.examples.appdb.tables.Planet.PLANET;

    /**
     * No further instances allowed
     */
    private Appdb() {
        super("appdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Planet.PLANET);
    }
}
