/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb;


import com.softwareaws.xray.examples.appdb.tables.Planet;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>appdb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PLANET_PRIMARY = Indexes0.PLANET_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PLANET_PRIMARY = Internal.createIndex("PRIMARY", Planet.PLANET, new OrderField[] { Planet.PLANET.ID }, true);
    }
}
