/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb;


import com.softwareaws.xray.examples.appdb.tables.Planet;
import com.softwareaws.xray.examples.appdb.tables.records.PlanetRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>appdb</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PlanetRecord, UInteger> IDENTITY_PLANET = Identities0.IDENTITY_PLANET;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlanetRecord> KEY_PLANET_PRIMARY = UniqueKeys0.KEY_PLANET_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PlanetRecord, UInteger> IDENTITY_PLANET = Internal.createIdentity(Planet.PLANET, Planet.PLANET.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PlanetRecord> KEY_PLANET_PRIMARY = Internal.createUniqueKey(Planet.PLANET, "KEY_planet_PRIMARY", Planet.PLANET.ID);
    }
}
