/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb;


import com.softwareaws.xray.examples.appdb.tables.Planet;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in appdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>appdb.planet</code>.
     */
    public static final Planet PLANET = Planet.PLANET;
}
