/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb.tables.pojos;


import com.softwareaws.xray.examples.appdb.tables.interfaces.IPlanet;

import javax.annotation.processing.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Planet implements IPlanet {

    private static final long serialVersionUID = -100631796;

    private final UInteger id;
    private final String   name;

    public Planet(IPlanet value) {
        this.id = value.getId();
        this.name = value.getName();
    }

    public Planet(
        UInteger id,
        String   name
    ) {
        this.id = id;
        this.name = name;
    }

    @Override
    public UInteger getId() {
        return this.id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Planet other = (Planet) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Planet (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
