/*
 * This file is generated by jOOQ.
 */
package com.softwareaws.xray.examples.appdb.tables.records;


import com.softwareaws.xray.examples.appdb.tables.Planet;
import com.softwareaws.xray.examples.appdb.tables.interfaces.IPlanet;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetRecord extends UpdatableRecordImpl<PlanetRecord> implements Record2<UInteger, String>, IPlanet {

    private static final long serialVersionUID = -1926999375;

    /**
     * Setter for <code>appdb.planet.id</code>.
     */
    public PlanetRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>appdb.planet.id</code>.
     */
    @Override
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>appdb.planet.name</code>.
     */
    public PlanetRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>appdb.planet.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Planet.PLANET.ID;
    }

    @Override
    public Field<String> field2() {
        return Planet.PLANET.NAME;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public PlanetRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public PlanetRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlanetRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IPlanet from) {
        setId(from.getId());
        setName(from.getName());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanetRecord
     */
    public PlanetRecord() {
        super(Planet.PLANET);
    }

    /**
     * Create a detached, initialised PlanetRecord
     */
    public PlanetRecord(UInteger id, String name) {
        super(Planet.PLANET);

        set(0, id);
        set(1, name);
    }
}
